# Generated by Django 5.2 on 2025-08-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RecipeManager", "0004_recipeingredient"),
        ("TagManager", "0005_tag_description_tag_icon_tagtype_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipetag",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_tags",
                to="RecipeManager.recipe",
            ),
        ),
    ]
