# Generated by Django 5.2 on 2025-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RecipeManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
