# Generated by Django 5.2 on 2025-07-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngredientManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
